### ISSUE TITLE
Release 0.19 Linux_x64.7z contains an Windows Executable instead of a Linux one

### ISSUE THREAD

**Issue by ryukinix** [aQaTL/MAL#2]
# Description
I downloaded: https://github.com/aQaTL/MAL/releases/download/0.19/linux_x64.7z

So I saw a `mal.exe` file and it seems a weird choice of extension, but tried to execute as a normal Linux executable and didn't work as expected. So to confirm that it was indeed a Windows Executable,  tried with wine and worked fine.

EDIT: BTW, nice project. A few years ago (2016) I authored a similar project at [ryukinix/mal] written in Python, got a little popular and I had some userbase that helped me on the development. It was great. I liked. Unfortunately, due to myanimelist decision to kill your own legacy API due privacy/GDPR concerns, I archived the project. For that matter, after a few months I migrated to anilist too, because I was so furious about myanimelist. It's nice to get back with a friendly cli app to manage my animes :) and for my luck it supports anilist as default. Congratulations.

[ryukinix/mal]: https://github.com/ryukinix/mal

**Comment by aQaTL** [comment]
Thanks for the report, fixed it.

Thanks for the kind words, really nice to see that other people had similar idea about managing anime lists with a cli app :)
