### ISSUE TITLE
XDG Base Directory compliance

### ISSUE THREAD

**Issue by langedev** [aQaTL/MAL#4]
Currently MAL does not comply with XDG Base Directory Specifications. It puts its files in $HOME/.mal instead of $XDG_CONFIG_HOME/mal or $HOME/.config/mal as specified here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

The flow should probably be the app checks if any of $XDG_CONFIG_HOME/mal, $HOME/.conf/mal, and $HOME/mal are present and if they are then uses them, otherwise creates the directory in $XDG_CONFIG_HOME/mal.

We should be able to implement this by changing the code here: https://github.com/aQaTL/MAL/blob/f3534c82371025277850411fc3b22c36b61532ec/utils.go#L27

I'd be happy to make a pull request.

**Comment by aQaTL** [comment]
Hey! Pull requests are welcome :)
