### ISSUE TITLE
Seeing some double entries.

### ISSUE THREAD

**Issue by yash-278** [aQaTL/MAL#6]
I downloaded the binary file, configs are also generated properly, but I can't fire mal command from terminal. Not sure what's wrong.

**Comment by yash-278** [comment]
My bad. Didn't move binary in `usr/local/bin` to access it globally. Dumb mistake.

**Comment by yash-278** [comment]
![image](https://user-images.githubusercontent.com/47289327/184654884-b1048326-7d21-4bfa-943b-973cf0645fc5.png)

Some duplicated entries are shown, is this a intended behaviour ?

**Comment by aQaTL** [comment]
Hi, this looks weird. Can you try deleting the config dir? It's at `$HOME/.mal` or `$HOME/.config/mal` or $XDG_CONFIG_DIR/mal`

**Comment by yash-278** [comment]
Tried deleting them, but same issue.

It seems having them in multiple status lists affect the query. I won't say this is a big issue since It actually doesn't cause any problem with updating stats.

![Screenshot from 2022-08-16 09-37-57](https://user-images.githubusercontent.com/47289327/184796124-31002ee8-9c93-4198-8fb9-6d9e6ea7f69e.png)

![Screenshot from 2022-08-16 09-38-16](https://user-images.githubusercontent.com/47289327/184796133-5802de55-06f8-4667-aa33-e2a95ddc8978.png)

**Comment by aQaTL** [comment]
Hi, please download the latest version and see if it fixes the double entries: https://github.com/aQaTL/MAL/releases/tag/0.23
You don't need to delete config dir, just run `mal -r` to refresh caches

**Comment by yash-278** [comment]
Yep, it's properly working now.
