### ISSUE TITLE
Any plans on supporting 0-100 rating?

### ISSUE THREAD

**Issue by Dokkae6949** [aQaTL/MAL#9]
As the title says. Are there any plans of supporting 0-100 ratings because currently every rating form 90-99 or something like this gets a rating of 9 so now I have 10 anime with a rating of 9 and don't know the exact rating (99 is way better than 90)

**Comment by aQaTL** [comment]
Hey! The newest version has support for all scoring systems. It'll now use the scoring system you've picked in your anilist profile. 
Download 0.24 from: https://github.com/aQaTL/MAL/releases/tag/0.24
To see the change, you'll need to remove 2 files in the config directory (located at `$HOME/.mal`): 
- aniListCache.json
- aniListUser.json
After that, just run the app. 

Let me know if it works for you now!

**Comment by Dokkae6949** [comment]
Hmm. I can see that it now displays 0-100 but the sorting is kinda weird?
Also is the highest rated one supposed to be the first one / highest number? Its kinda confusing
EDIT: also the `*.json` files were located at `$HOME/.config/mal`

![image](https://user-images.githubusercontent.com/90514461/230922282-332c1cdd-89d4-4b60-8611-c850bb13286e.png)
![image](https://user-images.githubusercontent.com/90514461/230922294-ffb5b88a-f4eb-47a2-9690-584c65e79171.png)

**Comment by aQaTL** [comment]
Oh, looks I didn't implement the sorting option for AniList mode. By default, it sorts by last updated.

**Comment by aQaTL** [comment]
Created https://github.com/aQaTL/MAL/issues/10
